// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqPon1zP2uB0qos1cQ2R_hXXFAQQMT_9s',
    appId: '1:1024405071253:web:7c5aeb93dda964930fc29c',
    messagingSenderId: '1024405071253',
    projectId: 'neura-fa252',
    authDomain: 'neura-fa252.firebaseapp.com',
    storageBucket: 'neura-fa252.firebasestorage.app',
    measurementId: 'G-0BS3DZ0WDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcGyiOTK1r6XzWvU7XlrZDA1Zuh5_eXL8',
    appId: '1:1024405071253:android:54e4a841924b8b810fc29c',
    messagingSenderId: '1024405071253',
    projectId: 'neura-fa252',
    storageBucket: 'neura-fa252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3Vbk8XtTU-NFmIkIGUxPhciYtXNwjfE',
    appId: '1:1024405071253:ios:9bd725007c0653720fc29c',
    messagingSenderId: '1024405071253',
    projectId: 'neura-fa252',
    storageBucket: 'neura-fa252.firebasestorage.app',
    iosBundleId: 'com.example.neura',
  );
}
